#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/yunluo

PRODUCT_COPY_FILES += \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/AudioLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AudioLog_dynamic.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/AudioParamOptions_mgvi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_mgvi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VOW_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VOW_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VOW_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VOW_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_params.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_facebook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_facebook.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_instagram.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_instagram.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_line.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_line.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_messenger.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_messenger.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_simple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_simple.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_snapchat.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_snapchat.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_telegram.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_telegram.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_tiktok.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_tiktok.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_twitter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_twitter.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_front_whatsapp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_front_whatsapp.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_facebook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_facebook.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_instagram.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_instagram.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_line.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_line.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_messenger.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_messenger.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_simple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_simple.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_snapchat.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_snapchat.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_telegram.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_telegram.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_tiktok.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_tiktok.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_twitter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_twitter.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_whatsapp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_whatsapp.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/camera/morpho_lowlight_tuning_params_rear_zoom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_tuning_params_rear_zoom.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/cust_color.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/cust_color_dsi_l83_36_02_0a_cphy_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_dsi_l83_36_02_0a_cphy_vdo_mi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/cust_color_dsi_l83_44_02_0b_cphy_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_dsi_l83_44_02_0b_cphy_vdo_mi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/cust_color_dsi_l83_44_02_0c_cphy_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_dsi_l83_44_02_0c_cphy_vdo_mi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/default_pd_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/etc/default_pd_calibration.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/dsi_l83_36_02_0a_cphy_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_l83_36_02_0a_cphy_vdo_mi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/dsi_l83_44_02_0b_cphy_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_l83_44_02_0b_cphy_vdo_mi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/dsi_l83_44_02_0c_cphy_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_l83_44_02_0c_cphy_vdo_mi.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/android.hardware.security.keymint-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.beanpod.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/meow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/meow.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/screen_light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/screen_light.xml \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/sixa_aurisys_param/sixth_param.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sixa_aurisys_param/sixth_param.txt \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/sixa_aurisys_param/sixth_param_voip.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sixa_aurisys_param/sixth_param_voip.txt \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal-videochat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-videochat.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_596C.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_596C.csv \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_596D.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_596D.csv \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/gt9886_cfg_6877v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6877v01.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/gt9886_firmware_6877v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6877v01.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/gt9896s_cfg_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6789v01.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/gt9896s_firmware_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6789v01.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_nt36523_L83_fw01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36523_L83_fw01.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_nt36523_L83_fw02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36523_L83_fw02.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_nt36523_L83_mp01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36523_L83_mp01.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_nt36523_L83_mp02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36523_L83_mp02.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_ts_fw_144.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_144.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_ts_fw_jdi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_jdi.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/novatek_ts_fw_tm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_tm.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/sipa.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sipa.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc2_2_ram_bt_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1d_1_hdr.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc2_2_ram_bt_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1e_1_hdr.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc2_2_ram_mcu_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1d_1_hdr.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc2_2_ram_mcu_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1e_1_hdr.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc2_2_ram_wifi_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1d_1_hdr.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc2_2_ram_wifi_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1e_1_hdr.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_coeff.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/soc_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_patch.bin \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/0102030405060708090a0b0c0d0e0f10.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0102030405060708090a0b0c0d0e0f10.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/05120000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/05120000000000000000000000000000.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/8aaaf201246000007143fe4f7c823c80.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8aaaf201246000007143fe4f7c823c80.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/xiaomi/yunluo/proprietary/vendor/thh/ta/isee_model.json:$(TARGET_COPY_OUT_VENDOR)/thh/ta/isee_model.json

PRODUCT_PACKAGES += \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    libAVCSecureVencCA \
    libadpcmdec_mtk \
    libaedv \
    libbwc \
    libgz_gp_client \
    libgz_uree \
    libion_mtk \
    libion_ulit \
    libladder \
    libmp3dec_mtk \
    libthha \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libmtk_drvb \
    libHEVCdec_sa.ca7.android \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libhevce_sb.ca7.android \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    libvcodec_utility_plat.mt6789 \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvcodec_utility \
    libvcodec_utility_v3a \
    libvcodecdrv \
    libvcodecdrv_v3a \
    libvpudv3a_vcodec \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    hdr_capture \
    hdr_preview \
    hq_algoutils \
    hq_asd \
    android.hardware.bluetooth@1.1-impl-mediatek \
    audio.primary.mediatek \
    audio.r_submix.mediatek \
    gatekeeper.beanpod \
    hwcomposer.mtk_common \
    kmsetkey.beanpod \
    libSoftGatekeeper \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mt6789 \
    sound_trigger.primary.mt6789 \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    libCamera_gc08a3mipiraw_3rd_Capture \
    libCamera_gc08a3mipiraw_3rd_Preview \
    libCamera_gc08a3mipiraw_Doc_Capture \
    libCamera_gc08a3mipiraw_HDRMode_Capture \
    libCamera_gc08a3mipiraw_Night_Capture \
    libCamera_gc08a3mipiraw_QQ_Capture \
    libCamera_gc08a3mipiraw_Wechat_Capture \
    libCamera_gc08a3mipiraw_Zoom_Capture \
    libCamera_gc08a3mipiraw_Zoom_Capture4x \
    libCamera_gc08a3mipiraw_Zoom_Preview \
    libCamera_gc08a3mipiraw_Zoom_Preview4x \
    libCamera_gc08a3mipiraw_Zoom_Video2x \
    libCamera_gc08a3mipiraw_Zoom_Video4x \
    libCamera_hi846mipiraw_3rd_Capture \
    libCamera_hi846mipiraw_3rd_preview \
    libCamera_hi846mipiraw_HDRMode_Capture \
    libCamera_hi846mipiraw_QQ_Capture \
    libCamera_hi846mipiraw_Wechat_capture \
    libDefaultFpsActor \
    libFaceCenterAlgo \
    libFrameRecord \
    libJpgEncPipe \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libTEECommon \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarcsoft_beautyshot \
    libarcsoft_fbpre \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_super_night \
    libarcsoft_supernight \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libasn1c_mapi \
    libasn1c_mdmi \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocomponentengine_vendor \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libblisrc32_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libc++_shared \
    libcam.seninfn3d \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.lmv \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.warp \
    libcamera_scene \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libfacetracker \
    libfgauge_gm30 \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libheichal \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimsg_log \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    libmiresample \
    libmmagent \
    libmml \
    libmorpho.photosolid \
    libmorpho_Lowlight \
    libmpbase \
    libmsbc_mtk \
    libmtkcam_pipelinepolicy-aov \
    libmtkisp_metadata \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuron_graph_delegate.mtk \
    libneuron_platform \
    libnir_neon_driver_ndk.mtk.vndk \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    liboemcrypto \
    libpixelflinger \
    libpqframework \
    libremosaic_wrapper \
    libremosaiclib \
    librgbwlightsensor \
    librt_extamp_intf \
    libsixth \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libteei_daemon_vfs \
    libtflite_mtk \
    libtlcWidevineModularDrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvoiprec \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvpu \
    libwifi-hal-mtk \
    libwvhidl \
    libwvkeybox \
    libwvdrmengine \
    arm.graphics-V1-ndk_platform \
    gc08a3_mipi_raw_IdxMgr \
    gc08a3_mipi_raw_tuning \
    hi846_mipi_raw_IdxMgr \
    hi846_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_gc08a3mipiraw_Face_Capture \
    libCamera_gc08a3mipiraw_Scene_Capture \
    libCamera_gc08a3mipiraw_Scene_Capture_4cell \
    libCamera_gc08a3mipiraw_Scene_Preview \
    libCamera_gc08a3mipiraw_Scene_Preview_4k \
    libCamera_gc08a3mipiraw_Video_1080 \
    libCamera_gc08a3mipiraw_Video_4k \
    libCamera_hi846mipiraw_Face_Capture \
    libCamera_hi846mipiraw_Scene_Capture \
    libCamera_hi846mipiraw_Scene_Capture_4cell \
    libCamera_hi846mipiraw_Scene_Preview \
    libCamera_hi846mipiraw_Scene_Preview_4k \
    libCamera_hi846mipiraw_Video_1080 \
    libCamera_hi846mipiraw_Video_4k \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust_func \
    libaalservice \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiselector \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.ispfeature \
    libcamalgo.lsc \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vsf \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libdip_drv \
    libdip_postproc \
    libdpframework \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmsnr \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libstereoinfoaccessor_vsdof \
    libmtkcam_streaminfo_plugin-p1stt \
    sensors.touch.detect \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.beanpod.xml \
    android.hardware.security.secureclock-service.beanpod.xml \
    android.hardware.security.sharedsecret-service.beanpod.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    manifest_media_c2_V1_2_default.xml \
    bp_kmsetkey_ca \
    conninfra_loader \
    fuelgauged \
    fuelgauged_nvram \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.security.keymint@1.0-service.beanpod \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6789 \
    camerahalserver \
    tetheroffloadservice \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    kmsetkey \
    kmsetkey_isee \
    mi_thermald \
    netdagent \
    nvram_daemon \
    teei_daemon \
    v3avpud \
    wlan_assistant \
    wmt_launcher \
    wmt_loader
